// GENERATED by scripts/parity-fixture.py in the scratch-for-java repository.
// Do not edit: change src/examples/java/parity/ParityProbe.java there instead,
// re-record with ./scripts/parity.sh --record and run the script again.
//
// Every value below is one the desktop library prints. Where this test fails,
// the browser and the desktop have drifted apart, and the output of the two
// says exactly where.
//
// Only the stage-free half of the probe is here. A Stage needs WebGL, which
// node has not got, so sprite geometry and the hitbox cannot be checked this
// way - scripts/parity.sh holds the desktop to those, and ScratchTest.java
// holds the browser to the same signatures.
//
// A whole double reads as `50` here and `50.0` on the desktop, because the
// IDE prints every double through JavaScript's own string conversion. That
// is settled and will not change, so the expected values below have had the
// trailing .0 taken off. A wrong value still fails.

/**::
 * Scratch the browser reports what the desktop reports
 * { "libraries": ["scratch"], "expectedOutput": "round=3\nroundTo2=2.35\nmod=2\nmodPositive=1\nmodWraps=9\nmap=50\nconstrain=10\nlerp=2.5\nabs=3\nsqrt=2\nsin30=0.5\ncos60=0.5\natan1=45\nlog100=2\nfloor=-3\nceiling=-2\nmin=1\nmax=3\nvector=Vector2[3.0, 4.0]\nvector.length=5\nvector.angle=53.13010235415598\nvector.unit=Vector2[0.6, 0.8]\nvector.add=Vector2[4.0, 6.0]\nvector.dot=11\ncolor=Color[r=255.0, g=128.0, b=0.0]\ncolor.red=255\ncolor.green=128\ncolor.blue=0\ncolor.equals=true\nhue.red=0\nhue.green=252\nhue.blue=255\n" }
 */

// Operators are the Scratch blocks, not Java's arithmetic.
println("round=" + Operators.round(2.5));
println("roundTo2=" + Operators.round(2.345, 2));
println("mod=" + Operators.mod(-7, 3));
println("modPositive=" + Operators.mod(7, 3));
println("modWraps=" + Operators.mod(-1, 10));
println("map=" + Operators.map(5, 0, 10, 0, 100));
println("constrain=" + Operators.constrain(15, 0, 10));
println("lerp=" + Operators.lerp(0, 10, 0.25));
println("abs=" + Operators.absOf(-3));
println("sqrt=" + Operators.sqrtOf(4));
println("sin30=" + Operators.round(Operators.sinOf(30), 4));
println("cos60=" + Operators.round(Operators.cosOf(60), 4));
println("atan1=" + Operators.atanOf(1));
println("log100=" + Operators.logOf(100));
println("floor=" + Operators.floorOf(-2.5));
println("ceiling=" + Operators.ceilingOf(-2.5));
println("min=" + Operators.min(3, 1, 2));
println("max=" + Operators.max(3, 1, 2));

Vector2 v = new Vector2(3, 4);
println("vector=" + v);
println("vector.length=" + v.length());
println("vector.angle=" + v.angle());
println("vector.unit=" + v.unitVector());
println("vector.add=" + new Vector2(1, 2).add(new Vector2(3, 4)));
println("vector.dot=" + new Vector2(1, 2).dot(new Vector2(3, 4)));

Color c = new Color(255, 128, 0);
println("color=" + c);
println("color.red=" + c.getRed());
println("color.green=" + c.getGreen());
println("color.blue=" + c.getBlue());
println("color.equals=" + c.equals(new Color(255, 128, 0)));
Color hue = new Color(128);
println("hue.red=" + hue.getRed());
println("hue.green=" + hue.getGreen());
println("hue.blue=" + hue.getBlue());
