// GENERATED by scratch-for-java/scripts/browser-compatibility.py.
export const scratchBrowserVersion = "5.8.0-browser.1";
export const scratchDesktopVersion = "5.8.0";
export const scratchBrowserMembers = [
  {
    "id": "AnimatedSprite/addAnimation",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/clone",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/getAnimationFrame",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/getAnimationInterval",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/isAnimationPlayed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/playAnimation",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/resetAnimation",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/setAnimationFrame",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/setAnimationInterval",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "AnimatedSprite/toString",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Circle/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/getDay",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/getDayOfWeek",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/getDaysSince2000",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/getHour",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/getMillisecond",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/getMinute",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/getMonth",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/getSecond",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Clock/getYear",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/changeColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/equals",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/get",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/getBlue",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/getGreen",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/getH",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/getHSB",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/getL",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/getRed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/getS",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/hashCode",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/setHSB",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/setRGB",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Color/toString",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Ellipse/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Hitbox/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Hitbox/contains",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Hitbox/getBounds",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Hitbox/getShape",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Hitbox/intersects",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Hitbox/translateAndRotateAndResize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "HtmlColor/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "HtmlColor/getRandom",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/absOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/acosOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/asinOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/atanOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/ceilingOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/constrain",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/cosOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/eToThePowerOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/floorOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/lerp",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/lnOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/logOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/map",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/max",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/min",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/mod",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/round",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/sinOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/sqrtOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/tanOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Operators/tenToThePowerOf",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/changeColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/changeSize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/changeTransparency",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/down",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/eraseAll",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/getColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/getSize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/goToBackground",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/goToForeground",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/goToMousePointer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/goToRandomPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/isInBackground",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/setColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/setPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/setSize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/setTransparency",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/stamp",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Pen/up",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Polygon/addPoint",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Polygon/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/noise",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/noiseSeed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/random",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/randomInt",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/randomPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/randomSeed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/randomVector2",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/randomX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Random/randomY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Rectangle/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Shape/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Shape/contains",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Shape/getBounds",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Shape/intersects",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Shape/rotate",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Shape/scale",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Shape/translate",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/addCostume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/addCostumes",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/addSound",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/ask",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/broadcast",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/changePosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/changeSize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/changeTint",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/changeTransparency",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/changeVolume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/changeX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/changeY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/clone",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/debug",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/deleteThisClone",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/disableHitbox",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/distanceToMousePointer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/distanceToSprite",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/enableHitbox",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getAnswer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getCurrentCostumeIndex",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getCurrentCostumeName",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getDeltaTime",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getDirection",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getHeight",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getHitbox",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getMouse",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getMouseX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getMouseY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getPen",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getShaders",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getSize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getStage",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getText",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getTimer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getTint",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getTouchingSprite",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getTouchingSprites",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getTransparency",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getVolume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getWidth",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/getY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/glide",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/goLayersBackwards",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/goLayersForwards",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/goToBackLayer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/goToFrontLayer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/goToMousePointer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/goToRandomPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/goToSprite",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/hide",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/hideVariable",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/ifOnEdgeBounce",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isAsking",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isClone",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isColorTouchingColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isGliding",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isKeyPressed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isMouseDown",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isSoundPlaying",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isTouchingColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isTouchingEdge",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isTouchingMousePointer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isTouchingSprite",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/isVisible",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/move",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/nextCostume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/pickRandom",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/playSound",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/pointInDirection",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/pointTowardsMousePointer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/pointTowardsSprite",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/previousCostume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/remove",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/run",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/say",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setDirection",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setHitbox",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setRotationCenter",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setRotationStyle",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setSize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setTint",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setTransparency",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setVolume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/setY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/show",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/showVariable",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/stamp",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/stopAllSounds",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/stopSound",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/switchCostume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/think",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/turnLeft",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/turnRight",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenAddedToStage",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenBackdropSwitches",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenClicked",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenIReceive",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenKeyPressed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenKeyReleased",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenMouseClicked",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenMouseMoved",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenRemovedFromStage",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Sprite/whenStartsAsClone",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/add",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/addBackdrop",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/addSound",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/ask",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/broadcast",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/changeColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/changeTint",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/changeTransparency",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/changeVolume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/count",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/debug",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/display",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/eraseAll",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/exit",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/find",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getAll",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getAnswer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getCamera",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getCurrentBackdropIndex",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getCurrentBackdropName",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getDeltaTime",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getFrameRate",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getHeight",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getMouse",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getMouseX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getMouseY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getPixels",
    "status": "desktop-only",
    "reason": "The desktop pixel buffer is not exposed by the browser renderer."
  },
  {
    "id": "Stage/getShaders",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getSorting",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getTimer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getVolume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/getWidth",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/hideVariable",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/isAsking",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/isDebug",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/isKeyPressed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/isMouseDown",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/isSoundPlaying",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/nextBackdrop",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/pickRandom",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/playSound",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/previousBackdrop",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/randomBackdrop",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/remove",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/removeAll",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/run",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/setColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/setCursor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/setDebug",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/setTint",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/setTransparency",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/setVolume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/showVariable",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/stopAllSounds",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/stopSound",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/switchBackdrop",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/wait",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/waitUntil",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/whenBackdropSwitches",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/whenIReceive",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/whenKeyPressed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/whenKeyReleased",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/whenMouseClicked",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Stage/whenMouseWheelMoved",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/addFont",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getAlign",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getCurrentFontIndex",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getCurrentFontName",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getDefaultFont",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getDefaultFontSize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getFont",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getStage",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getStyle",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getTextSize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getWidth",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/getY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/goLayersBackwards",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/goLayersForwards",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/goToBackLayer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/goToFrontLayer",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/isUI",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/nextFont",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/remove",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setAlign",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setBackgroundColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setFont",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setIsUI",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setStrokeColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setStyle",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setTextColor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setTextSize",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setWidth",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/setY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/showText",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/switchFont",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/useFont",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/useFontSizes",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/useSmoothing",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/whenAddedToStage",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Text/whenRemovedFromStage",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Timer/afterMillis",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Timer/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Timer/everyMillis",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Timer/forMillis",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Timer/intervalMillis",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Timer/millis",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Timer/reset",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Triangle/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "UISprite/changeHeight",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "UISprite/changeWidth",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "UISprite/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "UISprite/disableNineSlice",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "UISprite/setHeight",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "UISprite/setNineSlice",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "UISprite/setWidth",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/add",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/angle",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/clone",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/distance",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/distanceSq",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/dot",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/equals",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/fromPolar",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/getX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/getY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/hashCode",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/length",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/lengthSq",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/multiply",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/normalVector",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/reverse",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/rotateBy",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/rotateTo",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/sub",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/toString",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Vector2/unitVector",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/debug",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/exit",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/getDeltaTime",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/getGameSpeed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/getHeight",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/getInstance",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/getLibraryTitle",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/getLibraryVersion",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/getStage",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/getTextureSampling",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/getWidth",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/isDebug",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/isPaused",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/pause",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/resume",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/setDebug",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/setGameSpeed",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/setStage",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/step",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/transitionToStage",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/useFullScreen",
    "status": "desktop-only",
    "reason": "The embedded browser output uses its enclosing page; this desktop window option only reports a limitation."
  },
  {
    "id": "Window/useSplashLogo",
    "status": "desktop-only",
    "reason": "The browser has no desktop splash window. This option only reports a limitation."
  },
  {
    "id": "Window/useTextureSampling",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "Window/whenExits",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/changeX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/changeY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/changeZoom",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/getPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/getX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/getY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/getZoom",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/resetZoom",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/setPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/setX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/setY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/setZoom",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/setZoomLimit",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/toGlobalPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/toGlobalX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/toGlobalY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/toLocalPosition",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/toLocalX",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/camera/Camera/toLocalY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/fs/File/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/fs/File/load",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/fs/File/loadOrCreate",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/fs/File/loadXML",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/fs/File/loadXMLOrCreate",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/fs/File/save",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/fs/File/saveXML",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/pixels/Pixels/background",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/pixels/Pixels/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/pixels/Pixels/foreground",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/pixels/Pixels/main",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/FFmpegRecorder/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/FFmpegRecorder/saveFrame",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/FFmpegRecorder/stop",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/FrameRecorder/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/FrameRecorder/saveFrame",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/FrameRecorder/snapshot",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/GifRecorder/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/GifRecorder/saveFrame",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/GifRecorder/snapshot",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/GifRecorder/start",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/GifRecorder/stop",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/Recorder/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/Recorder/post",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/Recorder/saveFrame",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/Recorder/start",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/recorder/Recorder/stop",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/shader/Shader/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shader/getName",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shader/getPShader",
    "status": "desktop-only",
    "reason": "Processing's PShader object belongs to the desktop renderer. The browser uses WebGL filters."
  },
  {
    "id": "extensions/shader/Shader/set",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shader/setName",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shaders/add",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shaders/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shaders/get",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shaders/getCurrent",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shaders/getCurrentIndex",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shaders/getCurrentName",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shaders/next",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shaders/reset",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/shader/Shaders/switchTo",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/sorting/Sorting/by",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/sorting/Sorting/byY",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/sorting/Sorting/constructor",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/sorting/Sorting/getComparator",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/sorting/Sorting/isOn",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/sorting/Sorting/off",
    "status": "implemented",
    "reason": "Declared by the browser; behavioral limitations and compiler dialect differences still apply."
  },
  {
    "id": "extensions/tiled/MapObject/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/MapObject/getProperty",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/MapObject/getPropertyBoolean",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/MapObject/getPropertyFloat",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/MapObject/getPropertyInt",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/MapObject/getShape",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/MapObject/setClassName",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/Property/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/Property/setText",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/TiledMap/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/TiledMap/getObjectsFromLayer",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/TiledMap/stampLayerToBackground",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/TiledMap/stampLayerToForeground",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/TiledMap/toString",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  },
  {
    "id": "extensions/tiled/TilesetImage/constructor",
    "status": "desktop-only",
    "reason": "This API requires the desktop runtime. Browser declarations may report the limitation without performing the operation."
  }
];
