import { LibraryDeclarations } from "../../../module/libraries/DeclareType";
import { NonPrimitiveType } from "../../../types/NonPrimitiveType";
import { ObjectClass } from "../../system/javalang/ObjectClassStringClass";
import { ScratchColorClass } from "./ScratchColorClass";
import { SRC } from "./ScratchLibraryComments";

/**
 * The 141 named HTML colours, mirroring org.openpatch.scratch.HtmlColor.
 * Each is a ready-made Color, so `sprite.setTint(HtmlColor.CORNFLOWER_BLUE)`
 * works the same as on the desktop.
 */
export class ScratchHtmlColorClass extends ObjectClass {
    static __javaDeclarations: LibraryDeclarations = [
        { type: "declaration", package: "org.openpatch.scratch", signature: "class HtmlColor extends Object", comment: SRC.htmlColorClassComment },

        { type: "field", signature: "static Color ALICE_BLUE" },
        { type: "field", signature: "static Color ANTIQUE_WHITE" },
        { type: "field", signature: "static Color AQUA" },
        { type: "field", signature: "static Color AQUAMARINE" },
        { type: "field", signature: "static Color AZURE" },
        { type: "field", signature: "static Color BEIGE" },
        { type: "field", signature: "static Color BISQUE" },
        { type: "field", signature: "static Color BLACK" },
        { type: "field", signature: "static Color BLANCHED_ALMOND" },
        { type: "field", signature: "static Color BLUE" },
        { type: "field", signature: "static Color BLUE_VIOLET" },
        { type: "field", signature: "static Color BROWN" },
        { type: "field", signature: "static Color BURLYWOOD" },
        { type: "field", signature: "static Color CADET_BLUE" },
        { type: "field", signature: "static Color CHARTREUSE" },
        { type: "field", signature: "static Color CHOCOLATE" },
        { type: "field", signature: "static Color CORAL" },
        { type: "field", signature: "static Color CORNFLOWER_BLUE" },
        { type: "field", signature: "static Color CORNSILK" },
        { type: "field", signature: "static Color CRIMSON" },
        { type: "field", signature: "static Color CYAN" },
        { type: "field", signature: "static Color DARK_BLUE" },
        { type: "field", signature: "static Color DARK_CYAN" },
        { type: "field", signature: "static Color DARK_GOLDENROD" },
        { type: "field", signature: "static Color DARK_GRAY" },
        { type: "field", signature: "static Color DARK_GREEN" },
        { type: "field", signature: "static Color DARK_KHAKI" },
        { type: "field", signature: "static Color DARK_MAGENTA" },
        { type: "field", signature: "static Color DARK_OLIVE_GREEN" },
        { type: "field", signature: "static Color DARK_ORANGE" },
        { type: "field", signature: "static Color DARK_ORCHID" },
        { type: "field", signature: "static Color DARK_RED" },
        { type: "field", signature: "static Color DARK_SALMON" },
        { type: "field", signature: "static Color DARK_SEA_GREEN" },
        { type: "field", signature: "static Color DARK_SLATE_BLUE" },
        { type: "field", signature: "static Color DARK_SLATE_GRAY" },
        { type: "field", signature: "static Color DARK_TURQUOISE" },
        { type: "field", signature: "static Color DARK_VIOLET" },
        { type: "field", signature: "static Color DEEP_PINK" },
        { type: "field", signature: "static Color DEEP_SKY_BLUE" },
        { type: "field", signature: "static Color DIM_GRAY" },
        { type: "field", signature: "static Color DODGER_BLUE" },
        { type: "field", signature: "static Color FIREBRICK" },
        { type: "field", signature: "static Color FLORAL_WHITE" },
        { type: "field", signature: "static Color FOREST_GREEN" },
        { type: "field", signature: "static Color FUCHSIA" },
        { type: "field", signature: "static Color GAINSBORO" },
        { type: "field", signature: "static Color GHOST_WHITE" },
        { type: "field", signature: "static Color GOLD" },
        { type: "field", signature: "static Color GOLDENROD" },
        { type: "field", signature: "static Color GRAY" },
        { type: "field", signature: "static Color GREEN" },
        { type: "field", signature: "static Color GREEN_YELLOW" },
        { type: "field", signature: "static Color HONEYDEW" },
        { type: "field", signature: "static Color HOT_PINK" },
        { type: "field", signature: "static Color INDIAN_RED" },
        { type: "field", signature: "static Color INDIGO" },
        { type: "field", signature: "static Color IVORY" },
        { type: "field", signature: "static Color KHAKI" },
        { type: "field", signature: "static Color LAVENDER" },
        { type: "field", signature: "static Color LAVENDER_BLUSH" },
        { type: "field", signature: "static Color LAWN_GREEN" },
        { type: "field", signature: "static Color LEMON_CHIFFON" },
        { type: "field", signature: "static Color LIGHT_BLUE" },
        { type: "field", signature: "static Color LIGHT_CORAL" },
        { type: "field", signature: "static Color LIGHT_CYAN" },
        { type: "field", signature: "static Color LIGHT_GOLDENROD_YELLOW" },
        { type: "field", signature: "static Color LIGHT_GRAY" },
        { type: "field", signature: "static Color LIGHT_GREEN" },
        { type: "field", signature: "static Color LIGHT_PINK" },
        { type: "field", signature: "static Color LIGHT_SALMON" },
        { type: "field", signature: "static Color LIGHT_SEA_GREEN" },
        { type: "field", signature: "static Color LIGHT_SKY_BLUE" },
        { type: "field", signature: "static Color LIGHT_SLATE_GRAY" },
        { type: "field", signature: "static Color LIGHT_STEEL_BLUE" },
        { type: "field", signature: "static Color LIGHT_YELLOW" },
        { type: "field", signature: "static Color LIME" },
        { type: "field", signature: "static Color LIME_GREEN" },
        { type: "field", signature: "static Color LINEN" },
        { type: "field", signature: "static Color MAGENTA" },
        { type: "field", signature: "static Color MAROON" },
        { type: "field", signature: "static Color MEDIUM_AQUAMARINE" },
        { type: "field", signature: "static Color MEDIUM_BLUE" },
        { type: "field", signature: "static Color MEDIUM_ORCHID" },
        { type: "field", signature: "static Color MEDIUM_PURPLE" },
        { type: "field", signature: "static Color MEDIUM_SEA_GREEN" },
        { type: "field", signature: "static Color MEDIUM_SLATE_BLUE" },
        { type: "field", signature: "static Color MEDIUM_SPRING_GREEN" },
        { type: "field", signature: "static Color MEDIUM_TURQUOISE" },
        { type: "field", signature: "static Color MEDIUM_VIOLET_RED" },
        { type: "field", signature: "static Color MIDNIGHT_BLUE" },
        { type: "field", signature: "static Color MINT_CREAM" },
        { type: "field", signature: "static Color MISTY_ROSE" },
        { type: "field", signature: "static Color MOCCASIN" },
        { type: "field", signature: "static Color NAVAJO_WHITE" },
        { type: "field", signature: "static Color NAVY" },
        { type: "field", signature: "static Color OLD_LACE" },
        { type: "field", signature: "static Color OLIVE" },
        { type: "field", signature: "static Color OLIVE_DRAB" },
        { type: "field", signature: "static Color ORANGE" },
        { type: "field", signature: "static Color ORANGE_RED" },
        { type: "field", signature: "static Color ORCHID" },
        { type: "field", signature: "static Color PALE_GOLDENROD" },
        { type: "field", signature: "static Color PALE_GREEN" },
        { type: "field", signature: "static Color PALE_TURQUOISE" },
        { type: "field", signature: "static Color PALE_VIOLET_RED" },
        { type: "field", signature: "static Color PAPAYA_WHIP" },
        { type: "field", signature: "static Color PEACH_PUFF" },
        { type: "field", signature: "static Color PERU" },
        { type: "field", signature: "static Color PINK" },
        { type: "field", signature: "static Color PLUM" },
        { type: "field", signature: "static Color POWDER_BLUE" },
        { type: "field", signature: "static Color PURPLE" },
        { type: "field", signature: "static Color RED" },
        { type: "field", signature: "static Color ROSY_BROWN" },
        { type: "field", signature: "static Color ROYAL_BLUE" },
        { type: "field", signature: "static Color SADDLE_BROWN" },
        { type: "field", signature: "static Color SALMON" },
        { type: "field", signature: "static Color SANDY_BROWN" },
        { type: "field", signature: "static Color SEA_GREEN" },
        { type: "field", signature: "static Color SEASHELL" },
        { type: "field", signature: "static Color SIENNA" },
        { type: "field", signature: "static Color SILVER" },
        { type: "field", signature: "static Color SKY_BLUE" },
        { type: "field", signature: "static Color SLATE_BLUE" },
        { type: "field", signature: "static Color SLATE_GRAY" },
        { type: "field", signature: "static Color SNOW" },
        { type: "field", signature: "static Color SPRING_GREEN" },
        { type: "field", signature: "static Color STEEL_BLUE" },
        { type: "field", signature: "static Color TAN" },
        { type: "field", signature: "static Color TEAL" },
        { type: "field", signature: "static Color THISTLE" },
        { type: "field", signature: "static Color TOMATO" },
        { type: "field", signature: "static Color TURQUOISE" },
        { type: "field", signature: "static Color VIOLET" },
        { type: "field", signature: "static Color WHEAT" },
        { type: "field", signature: "static Color WHITE" },
        { type: "field", signature: "static Color WHITE_SMOKE" },
        { type: "field", signature: "static Color YELLOW" },
        { type: "field", signature: "static Color YELLOW_GREEN" },
        { type: "method", signature: "static Color getRandom()", native: ScratchHtmlColorClass._getRandom, comment: SRC.htmlColorGetRandomComment },
    ];

    static type: NonPrimitiveType;

    static _getRandom(): ScratchColorClass {
        const names = Object.keys(ScratchHtmlColorClass.HEX);
        const name = names[Math.floor(Math.random() * names.length)];
        return ScratchColorClass.fromHex(ScratchHtmlColorClass.HEX[name]);
    }

    /** Hex value per name; the static fields are filled from this below. */
    private static readonly HEX: Record<string, string> = {
            ALICE_BLUE: "#F0F8FF",
            ANTIQUE_WHITE: "#FAEBD7",
            AQUA: "#00FFFF",
            AQUAMARINE: "#7FFFD4",
            AZURE: "#F0FFFF",
            BEIGE: "#F5F5DC",
            BISQUE: "#FFE4C4",
            BLACK: "#000000",
            BLANCHED_ALMOND: "#FFEBCD",
            BLUE: "#0000FF",
            BLUE_VIOLET: "#8A2BE2",
            BROWN: "#A52A2A",
            BURLYWOOD: "#DEB887",
            CADET_BLUE: "#5F9EA0",
            CHARTREUSE: "#7FFF00",
            CHOCOLATE: "#D2691E",
            CORAL: "#FF7F50",
            CORNFLOWER_BLUE: "#6495ED",
            CORNSILK: "#FFF8DC",
            CRIMSON: "#DC143C",
            CYAN: "#00FFFF",
            DARK_BLUE: "#00008B",
            DARK_CYAN: "#008B8B",
            DARK_GOLDENROD: "#B8860B",
            DARK_GRAY: "#A9A9A9",
            DARK_GREEN: "#006400",
            DARK_KHAKI: "#BDB76B",
            DARK_MAGENTA: "#8B008B",
            DARK_OLIVE_GREEN: "#556B2F",
            DARK_ORANGE: "#FF8C00",
            DARK_ORCHID: "#9932CC",
            DARK_RED: "#8B0000",
            DARK_SALMON: "#E9967A",
            DARK_SEA_GREEN: "#8FBC8F",
            DARK_SLATE_BLUE: "#483D8B",
            DARK_SLATE_GRAY: "#2F4F4F",
            DARK_TURQUOISE: "#00CED1",
            DARK_VIOLET: "#9400D3",
            DEEP_PINK: "#FF1493",
            DEEP_SKY_BLUE: "#00BFFF",
            DIM_GRAY: "#696969",
            DODGER_BLUE: "#1E90FF",
            FIREBRICK: "#B22222",
            FLORAL_WHITE: "#FFFAF0",
            FOREST_GREEN: "#228B22",
            FUCHSIA: "#FF00FF",
            GAINSBORO: "#DCDCDC",
            GHOST_WHITE: "#F8F8FF",
            GOLD: "#FFD700",
            GOLDENROD: "#DAA520",
            GRAY: "#808080",
            GREEN: "#008000",
            GREEN_YELLOW: "#ADFF2F",
            HONEYDEW: "#F0FFF0",
            HOT_PINK: "#FF69B4",
            INDIAN_RED: "#CD5C5C",
            INDIGO: "#4B0082",
            IVORY: "#FFFFF0",
            KHAKI: "#F0E68C",
            LAVENDER: "#E6E6FA",
            LAVENDER_BLUSH: "#FFF0F5",
            LAWN_GREEN: "#7CFC00",
            LEMON_CHIFFON: "#FFFACD",
            LIGHT_BLUE: "#ADD8E6",
            LIGHT_CORAL: "#F08080",
            LIGHT_CYAN: "#E0FFFF",
            LIGHT_GOLDENROD_YELLOW: "#FAFAD2",
            LIGHT_GRAY: "#D3D3D3",
            LIGHT_GREEN: "#90EE90",
            LIGHT_PINK: "#FFB6C1",
            LIGHT_SALMON: "#FFA07A",
            LIGHT_SEA_GREEN: "#20B2AA",
            LIGHT_SKY_BLUE: "#87CEFA",
            LIGHT_SLATE_GRAY: "#778899",
            LIGHT_STEEL_BLUE: "#B0C4DE",
            LIGHT_YELLOW: "#FFFFE0",
            LIME: "#00FF00",
            LIME_GREEN: "#32CD32",
            LINEN: "#FAF0E6",
            MAGENTA: "#FF00FF",
            MAROON: "#800000",
            MEDIUM_AQUAMARINE: "#66CDAA",
            MEDIUM_BLUE: "#0000CD",
            MEDIUM_ORCHID: "#BA55D3",
            MEDIUM_PURPLE: "#9370DB",
            MEDIUM_SEA_GREEN: "#3CB371",
            MEDIUM_SLATE_BLUE: "#7B68EE",
            MEDIUM_SPRING_GREEN: "#00FA9A",
            MEDIUM_TURQUOISE: "#48D1CC",
            MEDIUM_VIOLET_RED: "#C71585",
            MIDNIGHT_BLUE: "#191970",
            MINT_CREAM: "#F5FFFA",
            MISTY_ROSE: "#FFE4E1",
            MOCCASIN: "#FFE4B5",
            NAVAJO_WHITE: "#FFDEAD",
            NAVY: "#000080",
            OLD_LACE: "#FDF5E6",
            OLIVE: "#808000",
            OLIVE_DRAB: "#6B8E23",
            ORANGE: "#FFA500",
            ORANGE_RED: "#FF4500",
            ORCHID: "#DA70D6",
            PALE_GOLDENROD: "#EEE8AA",
            PALE_GREEN: "#98FB98",
            PALE_TURQUOISE: "#AFEEEE",
            PALE_VIOLET_RED: "#DB7093",
            PAPAYA_WHIP: "#FFEFD5",
            PEACH_PUFF: "#FFDAB9",
            PERU: "#CD853F",
            PINK: "#FFC0CB",
            PLUM: "#DDA0DD",
            POWDER_BLUE: "#B0E0E6",
            PURPLE: "#800080",
            RED: "#FF0000",
            ROSY_BROWN: "#BC8F8F",
            ROYAL_BLUE: "#4169E1",
            SADDLE_BROWN: "#8B4513",
            SALMON: "#FA8072",
            SANDY_BROWN: "#F4A460",
            SEA_GREEN: "#2E8B57",
            SEASHELL: "#FFF5EE",
            SIENNA: "#A0522D",
            SILVER: "#C0C0C0",
            SKY_BLUE: "#87CEEB",
            SLATE_BLUE: "#6A5ACD",
            SLATE_GRAY: "#708090",
            SNOW: "#FFFAFA",
            SPRING_GREEN: "#00FF7F",
            STEEL_BLUE: "#4682B4",
            TAN: "#D2B48C",
            TEAL: "#008080",
            THISTLE: "#D8BFD8",
            TOMATO: "#FF6347",
            TURQUOISE: "#40E0D0",
            VIOLET: "#EE82EE",
            WHEAT: "#F5DEB3",
            WHITE: "#FFFFFF",
            WHITE_SMOKE: "#F5F5F5",
            YELLOW: "#FFFF00",
            YELLOW_GREEN: "#9ACD32",
    };

    /**
     * The declarations above name static fields; this fills them in once the
     * class is loaded, so each is a real Color object rather than a string.
     */
    static initialiseColors() {
        for (const [name, hex] of Object.entries(ScratchHtmlColorClass.HEX)) {
            (ScratchHtmlColorClass as any)[name] = ScratchColorClass.fromHex(hex);
        }
    }
}

ScratchHtmlColorClass.initialiseColors();
